### PR TITLE
feat: adding missing alt text 

### LINKED ISSUE #463: missing alt text
**Describe the bug**
I did an accessibility test on the website, and the results showed that most of the images/icons were missing alt text.  Without them, the content of an image will not be available to screen reader users or when the image is unavailable. This can cause these users to have a harder time navigating the site.
**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
screenshot of accessibility issue

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mac
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

### PR DESCRIPTION
**Pull request by CBID2**
## Issue 
Closes #463 

## Description
This PR adds alt text to the icons on pingcap's doc website, making it easier for people who use screen readers to navigate the site.

### CODE REVIEW

**Comment by Yuiham** [comment]
The changes in the PR don't seem to solve the problem. Can you retry it [the way I replied](https://github.com/pingcap/website-docs/issues/463#issuecomment-1888845391)?

**Comment by CBID2** [comment]
> The changes in the PR don't seem to solve the problem. Can you retry it [the way I replied](https://github.com/pingcap/website-docs/issues/463#issuecomment-1888845391)?

Sure @Yuiham! :) Can you also put the 2024-tidb-docs-dash label on my PR too? For some odd reason, it got removed.

**Comment by rpaik** [comment]
> > The changes in the PR don't seem to solve the problem. Can you retry it [the way I replied](https://github.com/pingcap/website-docs/issues/463#issuecomment-1888845391)?
> 
> Sure @Yuiham! :) Can you also put the 2024-tidb-docs-dash label on my PR too? For some odd reason, it got removed.

This was also discussed on Discord. The 2024-tidb-docs-dash label is not applicable for this PR.

**Comment by CBID2** [comment]
> the way I replied

Done @Yuiham! :)

**Comment by Yuiham** [comment]
> > the way I replied
> 
> Done @Yuiham! :)

Thank you for your great contribution! But the `docs` git submodule commits in your fork repository need to be excluded from this PR. Otherwise, it will cause a doc site build error. Can you try to run the following git command?

```bash
# Revert the submodule update commits
git revert --no-edit 00f3cf8...d450ed6

# Push reverting commits to remote
git push
```

**Comment by Yuiham** [comment]
LGTM for the rest

**Comment by CBID2** [comment]
> LGTM for the rest

Done @Yuiham

**Review by Yuiham — APPROVED** [review]

**Pull request merged**
